default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  min_messages: WARNING
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: serviceworker_rails_sandbox_development

test:
  <<: *default
  database: serviceworker_rails_sandbox_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
